# Generated by Django 3.2 on 2022-03-01 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pessoa',
            name='descricao',
            field=models.TextField(default=None, max_length=400, verbose_name='Comte um pouco sobre voce'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pessoa',
            name='descricao2',
            field=models.CharField(default=None, max_length=100, verbose_name='Pequena descrição'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='telefone2',
            field=models.CharField(default='', max_length=20, verbose_name='Telefone 2'),
        ),
    ]
