# Generated by Django 3.2 on 2022-03-01 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20220228_2128'),
    ]

    operations = [
        migrations.CreateModel(
            name='Projetos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criacao', models.DateField(auto_now_add=True, verbose_name='Criação')),
                ('atualizacao', models.DateTimeField(auto_now=True, verbose_name='Atualização')),
                ('ativo', models.BooleanField(default=False, verbose_name='Ativo')),
                ('projetost', models.IntegerField(verbose_name='Projetos em andamento')),
                ('projetosend', models.IntegerField(verbose_name='Projetos finalizados')),
                ('premios', models.IntegerField(verbose_name='Premios recebidos')),
                ('clientes', models.IntegerField(verbose_name='Clientes satisfeitos')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
