# Generated by Django 3.2 on 2022-03-01 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_projetos'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='portifolio',
            options={'verbose_name': 'Portifolio', 'verbose_name_plural': 'Portifolios'},
        ),
        migrations.AlterModelOptions(
            name='projetos',
            options={'verbose_name': 'Contagem', 'verbose_name_plural': 'Contagens'},
        ),
        migrations.AlterField(
            model_name='educacao',
            name='ensino',
            field=models.CharField(max_length=100, verbose_name='Estudou oque'),
        ),
        migrations.AlterField(
            model_name='educacao',
            name='fim',
            field=models.CharField(max_length=50, verbose_name='mes/ano do termino'),
        ),
        migrations.AlterField(
            model_name='educacao',
            name='inicio',
            field=models.CharField(max_length=50, verbose_name='mes/ano de inicio'),
        ),
        migrations.AlterField(
            model_name='educacao',
            name='instituicao',
            field=models.CharField(max_length=100, verbose_name='Nome da Instituição'),
        ),
        migrations.AlterField(
            model_name='servico',
            name='descricao',
            field=models.CharField(max_length=100, verbose_name='Descrição do serviço'),
        ),
        migrations.AlterField(
            model_name='servico',
            name='servico',
            field=models.CharField(max_length=50, verbose_name='Serviço'),
        ),
    ]
