# Generated by Django 3.2 on 2022-03-01 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20220301_1206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pessoa',
            name='linkedin',
            field=models.CharField(default='#', max_length=100, verbose_name='Linkedin'),
        ),
    ]
