# Generated by Django 3.2 on 2022-03-01 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_pessoa_linkedin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='educacao',
            name='fim',
            field=models.CharField(max_length=100, verbose_name='mes/ano do termino'),
        ),
        migrations.AlterField(
            model_name='educacao',
            name='inicio',
            field=models.CharField(max_length=100, verbose_name='mes/ano de inicio'),
        ),
        migrations.AlterField(
            model_name='experiencia',
            name='cargo',
            field=models.CharField(max_length=100, verbose_name='Cargo'),
        ),
        migrations.AlterField(
            model_name='experiencia',
            name='empresa',
            field=models.CharField(max_length=100, verbose_name='Nome da empresa'),
        ),
        migrations.AlterField(
            model_name='experiencia',
            name='fim',
            field=models.CharField(max_length=50, verbose_name='mes/ano do termino'),
        ),
        migrations.AlterField(
            model_name='experiencia',
            name='inicio',
            field=models.CharField(max_length=50, verbose_name='mes/ano de inicio'),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='cidade',
            field=models.CharField(max_length=50, verbose_name='Cidade/bairro'),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='descricao2',
            field=models.CharField(max_length=150, verbose_name='Pequena descrição'),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='facebook',
            field=models.CharField(default='#', max_length=300, verbose_name='Facebook'),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='instagram',
            field=models.CharField(default='#', max_length=300, verbose_name='instagram'),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='linkedin',
            field=models.CharField(default='#', max_length=300, verbose_name='Linkedin'),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='pais',
            field=models.CharField(max_length=50, verbose_name='Pais'),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='telefone1',
            field=models.CharField(max_length=50, verbose_name='Telefone 1'),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='telefone2',
            field=models.CharField(default='', max_length=50, verbose_name='Telefone 2'),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='twitter',
            field=models.CharField(default='#', max_length=300, verbose_name='twitter'),
        ),
        migrations.AlterField(
            model_name='servico',
            name='descricao',
            field=models.CharField(max_length=200, verbose_name='Descrição do serviço'),
        ),
        migrations.AlterField(
            model_name='servico',
            name='servico',
            field=models.CharField(max_length=100, verbose_name='Serviço'),
        ),
    ]
